# Generated by Django 5.0.1 on 2024-01-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('UserID', models.IntegerField(primary_key=True, serialize=False)),
                ('Phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField()),
                ('Surname', models.CharField()),
                ('Username', models.CharField()),
            ],
        ),
    ]
